import './globals.css'
import { Albert_Sans } from 'next/font/google'

const albertSans = Albert_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={albertSans.className}>{children}</body>
    </html>
  )
}
